# Dependabot configuration file
# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Set a limit on the number of open pull requests Dependabot can have
    open-pull-requests-limit: 10
    # Allow up to 5 pull requests for security updates
    pull-request-branch-name:
      separator: "-"
    # Specify reviewers for pull requests
    reviewers:
      - "nsxdavid"
    # Specify the versioning strategy
    versioning-strategy: auto
    # Allow only security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "github-actions"
      - "dependencies"
    open-pull-requests-limit: 5
    reviewers:
      - "nsxdavid"
